theme: jekyll-theme-minimal
title: Vit "Vitya" Novacek
description: A meager web presence of one academic ape [a possibly relevant disclaimer - if you have an impression that this place is not very much up to date, you may not be entirely wrong; the last touch up happened in August 2023, which results in a rather horrendous once-in-three years update frequency at the moment, ahem]
logo: img/vit_recent.jpg
show_downloads: false
google_analytics: UA-179496128-1
docs_list_title: Navigation
docs:

- title: Professional bio
  url: bio.html

- title: Contact information
  url: contact.html

- title: Quick intro
  url: index.html
  
- title: Not so professional bio
- url: life.html

- title: Research scribblings
- url: publications.html

- title: Scientific mysteries
- url: research.html

- title: Preaching knowledge
- url: teaching.html
