theme: jekyll-theme-minimal
title: Vit "Vitya" Novacek
description: A meager web presence of one academic ape
logo: img/vit_recent.jpg
show_downloads: false
google_analytics: UA-179496128-1
docs_list_title: Navigation
docs:

- title: Professional bio
  url: bio.html

- title: Contact information
  url: contact.html

- title: Quick intro
  url: index.html
  
- title: Not so professional bio
- url: life.html

- title: Research scribblings
- url: publications.html

- title: Scientific mysteries
- url: research.html

- title: Preaching knowledge
- url: teaching.html
